### PR TITLE
add pomodoro settings number inputs

### PR DESCRIPTION
**Pull request by jmbothe**
## Purpose
* Add `input type=number` to pomdoro settings
* address issue #110 

## Approach/Fixes
* Feature addition

## Testing
* Checkout this PR and fire up `gulp`
* goto pomodoro settings and click on the number next to slider
* enter a number and confirm that pomodoro period is updated
* test all settings to make sure nothing is broken :) thanks.

### CODE REVIEW

**Comment by ziggysauce** [comment]
@jmbothe Looks good! If there's a way to save the entered value when the user clicks off that would help with the UX but otherwise I can merge and release an update!

**Comment by jmbothe** [comment]
Hey @ziggysauce . Thanks for reviewing this. From my perspective, when the user clicks away without hitting `enter`, that is like they are aborting, so we wouldn't want whatever is in the `input` to be saved. That is how the username part of the greeting is setup as well. Let me know what you think.

Also, hold off on merging this cuz I wanna push one more commit to fix one little thing with the input.

**Comment by ziggysauce** [comment]
@jmbothe Ah, yes I understand that! Sounds good. I'll hold off for now, just let me know when you're ready and I'll work up the PR for the updates (including the HTML, manifest, etc.)

**Comment by jmbothe** [comment]
@ziggysauce cool. I should have something later today. thanks :)

**Comment by jmbothe** [comment]
@ziggysauce ok all good to go. let me know what you think. thanks!

**Pull request merged**
